### ISSUE TITLE
Opus PTime issue

### ISSUE THREAD

**Issue by smartbyte** [seanbright/asterisk-opus#23]
I think I have a ptime issue.
If I call a Fritzbox it sets the packetsize to 240 instead of 160 (so a ptime of 30 instead of 20), the audio sounds pretty choppy. Seems like the codec uses a ptime of 20 and the last 10 msec are cut off.

I found a patch for this problem in this asterisk opus implementaion:(https://github.com/meetecho/asterisk-opus). Is it possible to merge that patch into this implementation as well: (https://github.com/meetecho/asterisk-opus/commit/5211423832763329fb62ce579193ed4c476af91b#diff-bbb848a8f68dfd5ccf71fc6004b1b837)

Thanks, Joern.

**Comment by traud** [comment]
Since mid October, the 13.3 branch should be more advanced than the 11 branch, when it comes to ptime. Actually, everything _should_ be solved. Many 20/30 combinations were tested and are fine. Therefore, that commit is included already. Consequently, please, post more information about your setup, for example:
- Are you on the 13.3 branch of asterisk-opus?
- Which audio-codecs are involved. I guess, you are about a transcoding between G.722 (30 msec) and Open-Codec (20 msec). Correct?

**Comment by smartbyte** [comment]
O.K. now I feel **a bit** embarrassed: I deleted my asterisk sources (master-branch), did a new git clone. Re-Implemented my changes, installed your patch, and did another test, and, guess what: Problem is gone! :-( Sorry to bugger you!

**Comment by traud** [comment]
No bother at all. However, please note that [asterisk-opus](https://github.com/seanbright/asterisk-opus) was not tested with the current master branch of Asterisk (upcoming Asterisk 14), yet. Do you need anything special from the Asterisk master branch? Otherwise, I would stick with the Asterisk 13 branch.

**Comment by smartbyte** [comment]
I just like to have the newest version. ... But the patch seems to work with "Asterisk 14".
I cannot test it thoroughly, but from my experience as of now I am able to use it in my "private" environment.
Thanks for that.

**Comment by traud** [comment]
If you face that issue again, do not hesitate to re-open this or create a new issue report.
