### ISSUE TITLE
FEC & Packet loss percentage, can it be enabled?

### ISSUE THREAD

**Issue by verticelo** [seanbright/asterisk-opus#25]
Opus documentation states:
"FEC is only used by the encoder under certain conditions:
- The encoder must be told to expect loss via the OPUS_SET_PACKET_LOSS_PERC CTL
  Even when FEC is not used, telling the encoder about the expected level of loss will help it make more intelligent decisions. By default, the implementation assumes there is no loss."

Is it possible to set the packet loss percentage? For example, I would like to set it to 10%, is it possible?

I can't see in the code that it is currently being set.

**Comment by verticelo** [comment]
I see now that I was looking at the repo for @traud who pointed in his readme to open issues here. This issue might not be applicable to this repo. Apologies if that is the case.

**Comment by traud** [comment]
It is OK to raise the issue here. In the long run, that fork/branch is going to merge back with this one. However, I do not want to answer your question, because I do not have an answer actually. Instead, I want to give some inside, why I have not added this already. Perhaps I am on the wrong track, perhaps someone else finds an easier answer, hopefully someone adds that part of code one day. If it is me, you, or someone else, I would be happy about any contribution (even if it is just academic statistics that FEC is useful in that or that case).

In SIP/RTP, the receiver-packet-loss percentage is known through RTCP. Therefore, on the very long run, it is planned to detect the actual loss from RTCP. With that value, FEC can be changed adaptively (see [draft-ietf-rtcweb-fec](https://tools.ietf.org/html/draft-ietf-rtcweb-fec)). Consequently, you are asking for linking RTCP with the Opus Codec module. This could be added directly into the Asterisk core project. Although Opus Codec is one of the few audio codecs which benefit from such a new feature today, this limitation of the Asterisk architecture was unveiled with the audio codec SILK years ago already and continues to be there – until someone writes/tests/adds that source code to Asterisk.

One approach is to add a reference of `ast_rtp_instance` into the codec module itself. With the SIP channel driver `chan_sip`, this could happen within `channels/chan_sip.c:sip_write`. That is just an outline of an untested approach. I have to prioritize my work load here. Although this is an important feature for you, although this feature is on my list, others are more important. Consequently, you would have to code that yourself or find someone who does it for you on contract (for example as bug bounty via the mailing list [asterisk-dev](http://lists.digium.com/mailman/listinfo/asterisk-dev)).

Back to the question to set this value statically. To get a fixed value of 10%, you have to add the following line of code within `codecs/codec_opus.c:opus_encoder_construct`:
`status = opus_encoder_ctl(opvt->opus, OPUS_SET_PACKET_LOSS_PERC(10));`
and then the usual
`make`
`sudo make install`
from within your Asterisk source code directory.

**Comment by verticelo** [comment]
Thank you for the detailed answer.

We are planning to conduct (no date set) a series of tests with FEC. We will stream a known sound and then introduce a specific level of packet loss increasingly getting higher over a series of tests to see how FEC deals with it.

I can share the results here including the recordings whenever we have run the tests.

However, I do agree that the RTCP binding would be optimal but in the meantime the static works for us. We have a lot of users on cellular connections and I think (we will test it..) it would be beneficial for them to set a static level compared to have it completely disabled.

A different question, there is a enable_native_plc.patch file in the repo. In which cases would it be beneficial to apply that patch? Is it for specific Asterisk versions, or other codecs etc?

**Comment by traud** [comment]
Yes, please, share your results. I did some non-statistical tests via GSM/WCDMA/LTE with heavy handover scenarios (high-speed motorway in Germany) and was not able to hear any improvement with FEC. Therefore, it would be beneficial to have a concise test-scenario which is somehow reproducible. Or stated differently: I am just bridging the pieces together with that code. When it comes to testing, all I did was a ‘yes, it works’ test via Wi-Fi Roaming handover.

> there is a enable_native_plc.patch file in the repo. In which cases would it be beneficial to apply that patch? Is it for specific Asterisk versions, or other codecs etc?

That patch is required to leverage PLC/FEC of the Opus Codec in Asterisk. That patch enables PLC for all formats which support it. In case of Asterisk 13, these are iLBC and Speex. If you go for my fork, you get PLC/FEC for incoming Opus frames. Outgoing FEC must be activated as stated above. The patch is designed and tested for Asterisk 13. Ports exists for other branches. For more details, please, see [ASTERISK-25629…](https://issues.asterisk.org/jira/browse/ASTERISK-25629)
