### ISSUE TITLE
ASTERISK_FILE_VERSION is deprecated with Asterisk 14.0.0

### ISSUE THREAD

**Issue by philfry** [seanbright/asterisk-opus#27]
Hi,

Asterisk 14.0.0 was released and deprecated ASTERISK_FILE_VERSION in favour of ASTERISK_REGISTER_FILE:
```diff
diff --git i/codecs/codec_opus.c w/codecs/codec_opus.c
index 717d2f3..674b652 100644
--- i/codecs/codec_opus.c
+++ w/codecs/codec_opus.c
@@ -37,7 +37,7 @@

 #include "asterisk.h"

-ASTERISK_FILE_VERSION(__FILE__, "$Revision: $")
+ASTERISK_REGISTER_FILE()

 #include <opus/opus.h>

diff --git i/formats/format_vp8.c w/formats/format_vp8.c
index 47d9591..d4d6539 100644
--- i/formats/format_vp8.c
+++ w/formats/format_vp8.c
@@ -35,7 +35,7 @@

 #include "asterisk.h"

-ASTERISK_FILE_VERSION(__FILE__, "$Revision: $")
+ASTERISK_REGISTER_FILE()

 #include "asterisk/mod_format.h"
 #include "asterisk/module.h"
```
Disregard that, the patch compiles fine with Asterisk 14.

**Comment by traud** [comment]
Thank you for reporting! One cannot test all versions and configurations. For example, I am on the Asterisk 13 branch normally. Therefore it is always good to report such things. Thank you for the patch, because that helped to find the cause/solution much faster.

I am going to submit a Pull Request shortly – linking to this issue report. Furthermore, I made the change conditional so the source code stays compatible with Asterisk 13.7 and earlier. Thanks again for reporting and avoiding a headache for your fellows.
