### ISSUE TITLE
Update for Asterisk 14.0.1

### ISSUE THREAD

**Issue by amessina** [seanbright/asterisk-opus#28]
Asterisk 14.0.1 includes it's own method of downloading a precompiled codec_opus.so binary which phones home.  Maybe rename the codec so it can be enabled/disabled separately in menuslect.

**Comment by seanbright** [comment]
If the concern is that it phones home, just add a fake entry in `/etc/hosts` for `stats.asterisk.org` and it won't be able to.

**Comment by amessina** [comment]
@seanbright, it's not that it's my primary concern.  It didn't make sense to me that with all of the opus-related tools and your work to this point freely available to build against shared libraries, that Asterisk/Digium would need to create their own version with its own license.

Your suggestion is a good one however.  Thank you.

**Comment by seanbright** [comment]
Yeah, it doesn't make sense to me either, but what can you do?

**Comment by amessina** [comment]
I was thinking that there needs to be a way to include this version of codec opus in menuselect.  Right now if one disables 'codec_opus', you get a conflict as they're named the same.

Is your thought that this repository will eventually "go away" as opus support is beginning to move into Asterisk?

**Comment by seanbright** [comment]
[Yes.](https://github.com/seanbright/asterisk-opus/issues/29)

**Comment by amessina** [comment]
I completely understand. Thanks for pushing it to this point!

**Comment by traud** [comment]
Thank you for reporting! One cannot test all versions and configurations. For example, I am still with Asterisk 13.11.2. Therefore it is always good to report such things. Because the upcoming Asterisk 13.12 is going to face the same issue, I am reopening this issue report.

I am going to submit a Pull Request shortly – linking to this issue report. The change should be compatible with Asterisk 14.0.2 and 13.12, still retaining compatibility back to 13.3. If that did not fix your issue or a new regression was introduced, please, reopen this issue report.

Thanks again for reporting and avoiding a headache for your fellows.
