### ISSUE TITLE
NiceToHave: format_opus.c and ability to do playback of raw opus files

### ISSUE THREAD

**Issue by stokkeland** [seanbright/asterisk-opus#8]
As discussed briefly at irc:#asterisk - it would be awesome if there was a way to do playback of opus files to an opus channel without transcoding.

**Comment by konurbaev-e** [comment]
Is this issue relative to possibillity to use opus format in cmd Record smth like this?

exten => 802,n,Record(${STRFTIME(,,%Y-%m-%d_%H-%M-%S)}_${CALLERID(num)}_${CALLERID(dnid)}:opus,3,3)

**Comment by stokkeland** [comment]
I don't really know but sounds like that ability would depend on the same.
Who knows if this will ever happen, I recall Sean saying it is not straight forward.

**Comment by traud** [comment]
Thank you for requesting this feature. To know about demanded features helps to focus the development work.

Since Asterisk 13.12 (and Asterisk 14.0.1), this is supported by
A) enabling opus_codec via `make menuselect` or
B) downloading the module from [Digium Downloads](https://www.digium.com/products/asterisk/downloads) » Add-on Voice Codecs, or
C) downloading the module from [directly](http://downloads.digium.com/pub/telephony/codec_opus/).

Because these are binary modules not compatible with all UNIX platforms, the same module is available as Open-Source Software via the fork [github.com/traud/asterisk-opus…](https://github.com/traud/asterisk-opus) if something is missing or does not work as expected, please, create an issue report there.
